# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-06 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('text', models.CharField(max_length=90)),
                ('date', models.DateField(default=django.utils.datetime_safe.datetime.now)),
            ],
        ),
    ]
