# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-08 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_note_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tags',
        ),
        migrations.AddField(
            model_name='note',
            name='all_tags',
            field=models.ManyToManyField(blank=True, to='notes.Tag'),
        ),
    ]
