# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_note_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='all_tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
